### ISSUE TITLE
Atualizar README

### ISSUE THREAD

**Issue by gmmcal** [simples-controle/brasil-api#10]
Seria muito bom colocar instruções no README de como fazer o setup da aplicação, as dependências e suas respectivas versões e como fazer para rodar localmente.

**Comment by lukBarros** [comment]
Fiz uma atualização mínima: 

https://github.com/sururulab/brasil-api/commit/db2caa86983416a994e7b3f5463496fc7ecb396c

**Comment by lukBarros** [comment]
Versão base do arquivo feito @gmmcal
