### ISSUE TITLE
Criar CONTRIBUTING.md

### ISSUE THREAD

**Issue by gmmcal** [simples-controle/brasil-api#11]
Criar arquivo CONTRIBUTING.md com instruções dos passos para contribuir com o projeto. Isso deve incluir passo a passo sobre estrutura de branches e passo a passo para realizar o PR.

**Comment by lukBarros** [comment]
Ok! Muito bom vou fazer isto.

**Comment by lukBarros** [comment]
Fiz uma review básica no readme para quem quiser contribuir
