### ISSUE TITLE
CNPJ

### ISSUE THREAD

**Issue by rsmelo92** [simples-controle/brasil-api#12]
Pessoal, será que rola de adicionar uma consulta de CNPJ? Sem ser o cálculo, mas pra consultar na receita mesmo só se o cnpj existe ou não...

**Comment by lukBarros** [comment]
Fala @rsmelo92 precisamos básicamente de fonte de dados, seja um banco, um excel, uma outra API ou um site. Na verdade tem alguns sites cmo fonte que eu já hávia pesquisado, irei enfilerar isto para ser feito.

Se puder procurar fontes e citar, isso ajuda.

**Comment by marcelodeandrade** [comment]
O problema disso é conseguir uma `API` decente. A única que conheço é da [receitaws](https://www.receitaws.com.br/api).

**Comment by lukBarros** [comment]
@marcelodeandrade poderia ser essa mesma

**Comment by rodolfomenardi** [comment]
Também tem esse site que pode ser utilizado. :)

http://cnpj.info/

**Comment by lukBarros** [comment]
Ando sem tempo de implementar, assim que puder eu faço
