### ISSUE TITLE
Adicionar projeto ao Hacktoberfest

### ISSUE THREAD

**Issue by marcelodeandrade** [simples-controle/brasil-api#15]
A [Digital Ocean](https://digitalocean.com) lançou o [**Hacktoberfest**](https://hacktoberfest.digitalocean.com), "evento" que ocorrerá no mês de outubro e que tem como objetivo trazer novas contribuições para projetos opensource.

Conforme as [regras](https://hacktoberfest.digitalocean.com/#details) do evento, o label "Hacktoberfest" deve ser adicionado as issues para participar. 

Algumas dicas são dadas para melhorar a visibilidade do projeto no evento:

- Criar o `CONTRIBUTING.md` com um guia de pull requests para os desenvolvedores.
- Escolher issues com escopo bem definido e indenpendente.
- Adoção de um código de conduta para motivar o senso de comunidade.

**Comment by fernandovbs** [comment]
Quero contribuir com o projeto também. Como posso começar?

**Comment by lukBarros** [comment]
@fernandovbs da uma olhada nas issues, tem a demanda de fazer uma melhoria no site (visual) ou novas consultas por exemplo novas cotações em outras moedas, outra cotações de moedas digitais, etc.
Muito bem vindo ao time! Pena que perdemos a campanha que o @marcelodeandrade  citou só vim ver agora ;(
