### ISSUE TITLE
API DE CONSULTA DE CNPJ

### ISSUE THREAD

**Issue by lukBarros** [simples-controle/brasil-api#19]
Nova API de CNPJ.

Fonte possíveis

raspagem em https://pub.dataseek.com.br/CNPJ/30724985000169/

captura de dados em https://receitaws.com.br/

Deveria seguir a mesma lógica de MERCADORIAS, ou seja busca na fonte externa, persiste na interna e devolve. Num segundo momento busca retorna só da interna quando já tiver persistido lá.

**Comment by dataseeek** [comment]
Baixa a base completa da RF. http://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj . Eu sou responsável pelo https://pub.dataseeek.com.br , não quero robo lá consumindo banda. Valeu
