### ISSUE TITLE
Usar API no domínio e HTTPS

### ISSUE THREAD

**Issue by vinyvicente** [simples-controle/brasil-api#4]
É uma sugestão.

Usar um dominio api.brasilapi... e usar https no site e API, para segurança.

Usa um cloud firewall como Cloudflare, que tem https embutido e ssl junto (free basic).

**Comment by lukBarros** [comment]
Ok, dá para fazer isso sim, dá pra usar LetsCrypt o que vc acha?

**Comment by lukBarros** [comment]
Sobre sub domínio acho que não soma nada em vantagem o que somaria como vantagem a mudança?

**Comment by vinyvicente** [comment]
Padrão :)

api.github.com
api.facebook.com
api.netflix.com

**Comment by lukBarros** [comment]
Ok vou mdividir em 2 issues ok?

**Comment by lukBarros** [comment]
Veja #5  e #6
