### ISSUE TITLE
Layout de captcha zoado

### ISSUE THREAD

**Issue by guilhermejcgois** [simples-controle/brasil-api#7]
API legal, parabéns!

Não sei se já é sabido, mas o layout do captch está zoado:
![image](https://user-images.githubusercontent.com/1348723/29195126-45f8bb8c-7e03-11e7-98cf-0b6674037443.png)

- Windows 10
- Chrome Versão 59.0.3071.115 (Versão oficial) 64 bits
- Resolução: 1680 x 1050

**Comment by lukBarros** [comment]
Fala @guilhermejcgois  beleza cara! Obrigado pelo feedback, precisamos resolver isso via CSS pois essas views vem de outro componente de terceiro.

Isseu aberta para ser ressolvido, se quiser pode mandar o PR, sua ajuda é muito bem vinda!

**Comment by lukBarros** [comment]
@rsmelo92 olha essa por favor
